version: "3.7"

services:
  fastapi:
    image: fastapi
    build: .
    container_name: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8000:8000"
    networks:
      - cobo

networks:
  cobo:
